config:
  #游戏是否在运行 true 运行 false 未运行
  start: false
  #游戏是否已暂停 true 已暂停 false 未有暂停记录
  suspend: false
  #初始时间 (分钟)
  time : 30
  #踩方块获得时间
  block_time:
    #铁块
    IRON_BLOCK: 160
    #粗铁块
    RAW_IRON_BLOCK: 80
    #金块
    GOLD_BLOCK: 360
    #粗金块
    RAW_GOLD_BLOCK: 180
    #钻石块
    DIAMOND_BLOCK: 2400
    #绿宝石块
    EMERALD_BLOCK: 1500
    #远古残骸
    ANCIENT_DEBRIS: 150
    #合金块
    NETHERITE_BLOCK: 5400
  #击杀玩家获得死亡王佳损失的时间 百分数 0为不获得 100为全部获得
  kill: 50
  #死亡损失时间 百分数 0为不损失 100为全部
  death: 50


