name: TimeTrap
version: '${project.version}'
main: timetrap.timetrap.TimeTrap
api-version: 1.19
authors: [ 沐泽 ]
description: TimeTrap
commands:
  TimeTrap:
    description: 时间陷阱
    aliases: [ tt,Timetrap ]
    permission: timetrap
    permission-message: 您没有权限执行该命令
permissions:
  timetrap:
    description: 时间陷阱
    default: true
  timetrap.op:
    description: 时间陷阱
    default: op
  timetrap.pay:
    description: 交易权限
    default: true
  timetrap.list:
    description: 排行权限
    default: true